#!/bin/sh

set -eu

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
echo "${red}red text ${green}green text${reset}"

if ! cargo fmt -- --check
then
    echo "${red}There are some code style issues.${reset}"
    echo "${red}Run ${green}cargo fmt${reset} first."
	cargo fmt
    exit 1
fi

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
	cargo clippy
    exit 1
fi

if ! cargo test
then
    echo "There are some test issues."
    exit 1
fi

exit 0

COMMIT_MSG_FILE=$1

MESSAGE=$(cat $COMMIT_MSG_FILE)

if cog verify "$MESSAGE"; then
    echo "Commit parse succeeded"
else 
    echo "See https://www.conventionalcommits.org/en/v1.0.0"
    exit 1
fi

