FROM rust:1.61 AS builder
COPY . .
RUN cargo build --release

FROM debian:buster-slim
COPY --from=builder ./target/release/git-stats-bot ./target/release/git-stats-bot
CMD ["/target/release/git-stats-bot"]